[package]
name = "iot-gateway-collector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.23.0"
serialport = "4.2.0"
rumqttc = "0.18.0"
rand = "0.8.5"